.. A file containing links and substitutions
.. vim: ft=rst

.. Version control
.. _git: http://git-scm.com
.. _git parable: http://tom.preston-werner.com/2009/05/19/the-git-parable.html
.. _github: http://github.com

.. Editors
.. _vim: http://www.vim.org
.. _command-t: https://wincent.com/products/command-t
.. _command-t README: http://git.wincent.com/command-t.git/blob_plain/master:/README.txt

.. Python and common libraries
.. _python: http://www.python.org
.. _python.org releases: http://www.python.org/download/releases
.. _distutils: http://docs.python.org/2/library/distutils.html
.. _setuptools: http://pypi.python.org/pypi/setuptools
.. _distribute: http://pypi.python.org/pypi/distribute
.. _pip: http://pypi.python.org/pypi/pip
.. _numpy: http://www.numpy.org
.. _scipy: https://www.scipy.org/scipylib/index.html
.. _old and new python versions: https://launchpad.net/%7Efkrull/+archive/deadsnakes
.. _nose: http://readthedocs.org/docs/nose/en/latest
.. _nose-ipdb: https://github.com/flavioamieiro/nose-ipdb
.. _scipy stats t distribution:
.. _t distribution class:
   https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.t.html
.. _variables and scope:
    http://python-textbok.readthedocs.io/en/1.0/Variables_and_Scope.html
.. _python textbook:
.. _object oriented programming in python:
    http://python-textbok.readthedocs.io
.. _notebook on variable scope:
    http://nbviewer.jupyter.org/github/rasbt/python_reference/blob/master/tutorials/scope_resolution_legb_rule.ipynb
.. _string formatting:
    https://docs.python.org/3/library/string.html#format-string-syntax

.. Virtualenv and helpers
.. _virtualenv: http://pypi.python.org/pypi/virtualenv
.. _virtualenvwrapper: http://www.doughellmann.com/projects/virtualenvwrapper
.. _old and new python versions: https://launchpad.net/%7Efkrull/+archive/deadsnakes

.. Pypi and packaging
.. _pypi: http://pypi.python.org
.. _example pypi: http://packages.python.org/an_example_pypi_project/setuptools.html#intermezzo-pypirc-file-and-gpg

.. Mac development
.. _macports: http://www.macports.org
.. _github osx installation: http://help.github.com/mac-git-installation
.. _xcode: http://developer.apple.com/TOOLS/xcode
.. _macvim: https://github.com/b4winckler/macvim
.. _bdist_mpkg: http://pypi.python.org/pypi/bdist_mpkg
.. _parallels: http://www.parallels.com

.. Windows development
.. _mingw: http://www.mingw.org/wiki/Getting_Started
.. _msys: http://www.mingw.org/wiki/MSYS
.. _powershell: http://www.microsoft.com/powershell
.. _msysgit: http://code.google.com/p/msysgit
.. _putty: http://www.chiark.greenend.org.uk/~sgtatham/putty

.. Nipy and friends
.. _nipy: http://nipy.org
.. _gitwash: http://github.com/matthew-brett/gitwash

.. Mathematics
.. _summation:
.. _wikipedia on summation: https://en.wikipedia.org/wiki/Summation
.. _summation identities:
.. _wikipedia on summation identities:
   https://en.wikipedia.org/wiki/Summation#Identities
.. _rotation matrices:
.. _wikipedia on rotation matrices:
   https://en.wikipedia.org/wiki/Rotation_matrix
.. _vector projection:
.. _wikipedia on vector projection:
   https://en.wikipedia.org/wiki/Vector_projection
.. _scalar projection:
.. _wikipedia on scalar projection:
   https://en.wikipedia.org/wiki/Scalar_projection
.. _dot products and projections:
   http://www.math.oregonstate.edu/home/programs/undergrad/CalculusQuestStudyGuides/vcalc/dotprod/dotprod.html
.. _Pearson product-moment correlation coefficient:
   https://en.wikipedia.org/wiki/Pearson_product-moment_correlation_coefficient
.. _probability density function:
   https://en.wikipedia.org/wiki/Probability_density_function
.. _cumulative distribution function:
    https://en.wikipedia.org/wiki/Cumulative_distribution_function
.. _optimization:
    http://en.wikipedia.org/wiki/Mathematical_optimization

.. Licenses
.. _CC0 license: http://creativecommons.org/publicdomain/zero/1.0/legalcode

.. Neuroimaging stuff
.. _BOLD: https://en.wikipedia.org/wiki/Blood-oxygen-level_dependent
.. _blood-oxygen-level dependent: https://en.wikipedia.org/wiki/Blood-oxygen-level_dependent
.. _convolution: https://en.wikipedia.org/wiki/Convolution
.. _impulse response: https://en.wikipedia.org/wiki/Impulse_response
.. _boxcar function: https://en.wikipedia.org/wiki/Boxcar_function

.. People
.. _Sebastian Raschka: http://sebastianraschka.com/

.. Substitutions
.. |emdash| unicode:: U+02014
.. |--| unicode:: U+02014
